### ISSUE TITLE
Possibility of memory leak.

### ISSUE THREAD

**Issue by thefish1087** [thefish1087/Project-Euler#5]
Since I'm not pretty sure of how C# manages the memory data behind the scenes, when using `goto`, I rather find another approach.

https://github.com/thefish2191/ProjectEuler/blob/61de98c7ebfb9f744d3af04cd16960183f0c162d/Problem009.cs#L22

Possibly using a bool may solve the problem.

**Comment by thefish2191** [comment]
This issue will be fixed when migrating back to python
